"""add subscription markers

Revision ID: 4dc5633d30fa
Revises: 64389e32de89
Create Date: 2025-08-16 17:34:05.704571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc5633d30fa'
down_revision: Union[str, None] = '64389e32de89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_subscribed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('was_subscribed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'was_subscribed')
    op.drop_column('users', 'is_subscribed')
    # ### end Alembic commands ###
