"""init

Revision ID: d539580d3829
Revises: 
Create Date: 2025-08-12 20:01:34.334323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd539580d3829'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giveaways',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('integration_url', sa.String(), nullable=False),
    sa.Column('hide_integration', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('subscription_text', sa.String(), nullable=True),
    sa.Column('integration_text', sa.String(), nullable=True),
    sa.Column('success_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__giveaways'))
    )
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__media'))
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__settings')),
    sa.UniqueConstraint('key', name=op.f('uq__settings__key'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'tg_id', name=op.f('pk__users')),
    sa.UniqueConstraint('tg_id', name=op.f('uq__users__tg_id'))
    )
    op.create_table('giveaway_integration_media',
    sa.Column('giveaway_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], name=op.f('giveaway_integration_media_giveaway_id_fkey')),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('giveaway_integration_media_media_id_fkey')),
    sa.PrimaryKeyConstraint('giveaway_id', 'media_id', name=op.f('pk__giveaway_integration_media'))
    )
    op.create_table('giveaway_main_media',
    sa.Column('giveaway_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], name=op.f('giveaway_main_media_giveaway_id_fkey')),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('giveaway_main_media_media_id_fkey')),
    sa.PrimaryKeyConstraint('giveaway_id', 'media_id', name=op.f('pk__giveaway_main_media'))
    )
    op.create_table('giveaway_postbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], name=op.f('giveaway_postbacks_tg_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__giveaway_postbacks'))
    )
    op.create_table('giveaway_subscription_media',
    sa.Column('giveaway_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], name=op.f('giveaway_subscription_media_giveaway_id_fkey')),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('giveaway_subscription_media_media_id_fkey')),
    sa.PrimaryKeyConstraint('giveaway_id', 'media_id', name=op.f('pk__giveaway_subscription_media'))
    )
    op.create_table('giveaway_success_media',
    sa.Column('giveaway_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], name=op.f('giveaway_success_media_giveaway_id_fkey')),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('giveaway_success_media_media_id_fkey')),
    sa.PrimaryKeyConstraint('giveaway_id', 'media_id', name=op.f('pk__giveaway_success_media'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('giveaway_success_media')
    op.drop_table('giveaway_subscription_media')
    op.drop_table('giveaway_postbacks')
    op.drop_table('giveaway_main_media')
    op.drop_table('giveaway_integration_media')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('media')
    op.drop_table('giveaways')
    # ### end Alembic commands ###
