"""Addlogs table

Revision ID: f0bd4e9fe6e6
Revises: 4dc5633d30fa
Create Date: 2025-08-26 01:13:23.304680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0bd4e9fe6e6'
down_revision: Union[str, None] = '4dc5633d30fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('giveaway_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], name=op.f('user_actions_giveaway_id_fkey')),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], name=op.f('user_actions_tg_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_actions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_actions')
    # ### end Alembic commands ###
